import phronesis.CreateDatabaseTask
import org.flywaydb.gradle.task.FlywayMigrateTask

plugins {
	id 'java'
	id 'application'
	id 'jacoco'

	id 'org.flywaydb.flyway' version '12.9.0'
	id 'org.springframework.boot' version '3.4.3'
}

repositories {
	mavenCentral()
}

dependencies {
	implementation(
			'com.h2database:h2:2.3.232',
			'org.flywaydb:flyway-core:12.9.0',
			'org.jspecify:jspecify:1.0.0',
			'org.springframework.boot:spring-boot-h2console:4.0.3',
			'org.springframework.boot:spring-boot-starter-data-jpa:4.0.3',
			'org.springframework.boot:spring-boot-starter-security:4.0.3',
			'org.springframework.boot:spring-boot-starter-web:4.0.3'
	)

	testImplementation(
			'org.junit.jupiter:junit-jupiter-api:6.0.3',
			'org.springframework.boot:spring-boot-starter-test:4.0.3',
			'org.springframework.boot:spring-boot-starter-security-test:4.0.3',
			'org.springframework.boot:spring-boot-starter-webmvc-test:4.0.3'
	)
	testRuntimeOnly(
			'org.junit.jupiter:junit-jupiter-engine:6.0.3'
	)
}

bootJar {
	mainClassName = 'phronesis.Main'
}

tasks.withType(JavaCompile).all {
	options.compilerArgs.add("-Xlint:all")
}

task createDatabase(type: CreateDatabaseTask)

task migrateDatabase(type: FlywayMigrateTask) {
	dependsOn(createDatabase)

	// TODO: specify these a better way
	url = "jdbc:h2:" + project.projectDir.getAbsolutePath() + "/database"
	user = "sa"
	password = "password"

	doLast {
		println("migrateDatabase complete")
	}
}

task migrateTestDatabase(type: FlywayMigrateTask) {
	dependsOn(createDatabase)

	// TODO: specify these a better way
	url = "jdbc:h2:" + project.projectDir.getAbsolutePath() + "/database-test"
	user = "sa"
	password = "password"

	doLast {
		println("migrateTestDatabase complete")
	}
}

test {
	dependsOn(migrateDatabase, migrateTestDatabase)
	finalizedBy(jacocoTestReport)

	testLogging {
		events "passed", "skipped", "failed"
		outputs.upToDateWhen { false }
		showStandardStreams = true
	}

	useJUnitPlatform()
}

jacoco {
	toolVersion = "0.8.14"
}

jacocoTestReport {
	reports {
		xml.required.set(false)
		csv.required.set(false)
		html.required.set(true)
	}
}
