# turn off the default connect to Flyway - we'll handle that ourselves
spring.flyway.enabled=false

# log what happens with unsuccessful requests
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG